### ISSUE TITLE
_episodes_rmd/04-Decision-Forests.Rmd: Minor code edit or addition

### ISSUE THREAD

**Issue by gmcdonald-sfg** [djhunter/r-ml-tabular-data#13]
In the first challenge, an alternative to the two lines of code “rwp <- predict(rwtree, testDF) rwpred <- ifelse(rwp[,1] > 0.5,  "bad", "good")” would simply be “rwpred <- predict(rwtree, testDF, type = "class")”. This could be a helpful thing to show the learners.

**Comment by djhunter** [comment]
I'll put this in the instructor notes.
